# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(973, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(128, 128))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.sheppLogan_button = QtWidgets.QPushButton(self.tab)
        self.sheppLogan_button.setObjectName("sheppLogan_button")
        self.gridLayout_3.addWidget(self.sheppLogan_button, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.size_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.size_comboBox.setObjectName("size_comboBox")
        self.size_comboBox.addItem("")
        self.size_comboBox.addItem("")
        self.size_comboBox.addItem("")
        self.size_comboBox.addItem("")
        self.size_comboBox.addItem("")
        self.gridLayout_4.addWidget(self.size_comboBox, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.properties_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.properties_comboBox.setObjectName("properties_comboBox")
        self.properties_comboBox.addItem("")
        self.properties_comboBox.addItem("")
        self.properties_comboBox.addItem("")
        self.gridLayout_4.addWidget(self.properties_comboBox, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 1, 2, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 2, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 1, 1, 1)
        self.recovery_gragh = QtWidgets.QGraphicsView(self.tab)
        self.recovery_gragh.setObjectName("recovery_gragh")
        self.gridLayout_3.addWidget(self.recovery_gragh, 4, 1, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 5, 1, 1, 1)
        self.decay_grapgh = QtWidgets.QGraphicsView(self.tab)
        self.decay_grapgh.setObjectName("decay_grapgh")
        self.gridLayout_3.addWidget(self.decay_grapgh, 6, 1, 1, 2)
        self.browse_button = QtWidgets.QPushButton(self.tab)
        self.browse_button.setObjectName("browse_button")
        self.gridLayout_3.addWidget(self.browse_button, 0, 1, 1, 1)
        self.show_phantom_label = QtWidgets.QLabel(self.tab)
        self.show_phantom_label.setFrameShape(QtWidgets.QFrame.Box)
        self.show_phantom_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_phantom_label.setText("")
        self.show_phantom_label.setScaledContents(True)
        self.show_phantom_label.setAlignment(QtCore.Qt.AlignCenter)
        self.show_phantom_label.setObjectName("show_phantom_label")
        self.gridLayout_3.addWidget(self.show_phantom_label, 1, 0, 6, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 973, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sheppLogan_button.setText(_translate("MainWindow", "Shepp-Logan Phantom"))
        self.groupBox.setTitle(_translate("MainWindow", "Phantom Properties"))
        self.label_2.setText(_translate("MainWindow", "Size"))
        self.size_comboBox.setCurrentText(_translate("MainWindow", "Default"))
        self.size_comboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.size_comboBox.setItemText(1, _translate("MainWindow", "128x128"))
        self.size_comboBox.setItemText(2, _translate("MainWindow", "256x256"))
        self.size_comboBox.setItemText(3, _translate("MainWindow", "512x512"))
        self.size_comboBox.setItemText(4, _translate("MainWindow", "1024x1024"))
        self.label_3.setText(_translate("MainWindow", "Displayed Property"))
        self.properties_comboBox.setItemText(0, _translate("MainWindow", "T1"))
        self.properties_comboBox.setItemText(1, _translate("MainWindow", "T2"))
        self.properties_comboBox.setItemText(2, _translate("MainWindow", "Proton Density"))
        self.groupBox_2.setTitle(_translate("MainWindow", "RF Properties"))
        self.label_4.setText(_translate("MainWindow", "Time to Echo"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "milliseconds"))
        self.label_5.setText(_translate("MainWindow", "Time to Repeat"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "milliseconds"))
        self.label_6.setText(_translate("MainWindow", "Flipping Angel"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Degrees"))
        self.label_8.setText(_translate("MainWindow", "T1 Plot"))
        self.label_7.setText(_translate("MainWindow", "T2 Plot"))
        self.browse_button.setText(_translate("MainWindow", "Browse"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Part 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Part 2"))

